name: Manual WorkFlow

on:
  workflow_dispatch:
    inputs:
      employeeName:
       description: 'Employee Name'
       default: 'test'
       required: true
      employeeAge:
       description: 'Employee Age'
       required: true
      empAddress:
       description: 'Employee Address'
       required: true 
       default: 'Penang'
       
jobs:
  build-manual:
    runs-on: ubuntu-latest
    steps:
      - name: taking inputs
        run: echo "Employee Details as follows..."${{inputs.employeeName}} ${{inputs.employeeAge}}" ${{inputs.empAddress}}"

      - name: show separate line
        run :  |
          echo "Employee Details as follows.."
          echo "Name: ${{ inputs.employeeName }}"
          echo "Age: ${{ inputs.employeeAge }}"
