name: setUp-output-variables-release

on:
  push:
    branches: main

jobs:
  build-output:
    runs-on: ubuntu-latest

    steps:
      - name: set output variables
        id: set-out
        shell: bash
        run: echo "Name=ShanukaPerera" >> $GITHUB_OUTPUT

      - name: set output2 variables
        id: set-out2
        shell: bash
        run: $Name=shan >> $GITHUB_OUTPUT

      - name: access output
        run: echo ${{ steps.set-out2.outputs.Name }}
       
      
    
