name: setUp-output-variables-release

on:
  push:
    branches: main
    
env:
  var1: "shanuka"
 

jobs:
  build-output:
    runs-on: ubuntu-latest

    steps:
      - name: set output variables
        id: set-out
        shell: bash
        run: |
         echo "Name=${{ env.var1 }}" >> $GITHUB_OUTPUT
         echo "Age=37" >> $GITHUB_OUTPUT

     

      - name: access output
        run: echo "The value of Name is ${{ steps.set-out.outputs.Name }}"
       
      
    
